### ISSUE TITLE
HP_PDM filter output all zero

### ISSUE THREAD

**Issue by lvehe** [STMicroelectronics/fp-sns-allmems1#1]
I'm using MEMS PDM microphone and trying the new hp_pdm filter, I found 2 bugs below.
1) The new hp_pdm filter can only using  PDM_FILTER_DEC_FACTOR_64_HI_PERF and  PDM_FILTER_DEC_FACTOR_96_HI_PERF, otherwise it returns PDM_FILTER_DECIMATION_ERROR.
2) Even select PDM_FILTER_DEC_FACTOR_64_HI_PERF, PDM_Filter_Init and PDM_Filter_setConfig return 0. When PDM_Filter is called, all output data is just zero.

I used the old pmd filter before, and it output 32kHz and 16bits data, and it showed all ok.
Now I want to output 48kHz and 24bits data, so I tried the new hp_pdm filter. But it failed.

**Comment by mgrella** [comment]
Hello @lvehe 

I am very sorry for such a late answer.
In case you still need help, you can find a pre-built example of HP_PDM usage in the x-cube-memsmic1 repo:

[https://github.com/STMicroelectronics/x-cube-memsmic1/tree/main/Projects/STM32F401RE-Nucleo/Demonstration/CCA02M2/HP_Microphones_Streaming](url)

Please also note, as you can see in the repo README [(https://github.com/STMicroelectronics/x-cube-memsmic1#readme)](url), Known Limitations section, that you need the STEVAL-MIC006xx as add-on to CCA02M2.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/18306387/217285851-82085066-5b01-49f7-b51d-1f3d89157254.png)

Let us know if you need further assistance or if we can close the issue.

Thank you and best regards,
Marco

**Comment by mgrella** [comment]
Closing this issue, feel free to reopen it if you still are facing problems.

Best regards,
Marco
